# Training and test data sets for training and/or metrics evaluation
data:
  training:
    # Specify directory path to training dataset
    data_dir: data/coherent_euclid_dataset/
    # Provide name of training dataset
    file: train_Euclid_res_200_TrainStars_id_001.npy
  test:
    # Specify directory path to training dataset
    data_dir: data/coherent_euclid_dataset/
    # Provide name of test dataset
    file: test_Euclid_res_id_001.npy